apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firmups.fullname" . }}-env
  labels:
    {{- include "firmups.labels" . | nindent 4 }}
data:
  RUST_LOG: {{ .Values.app.logLevel | quote }}
  FIRMUPS_DB_NAME: {{ .Values.postgresql.database | quote }}
  FIRMUPS_DATA_PATH: "/opt/firmups/data"
  FIRMUPS_FIRMWARE_MAX_SIZE_BYTES: {{ .Values.app.firmwareMaxSizeBytes | int64 | quote }}
  FIRMUPS_STORAGE_TYPE: "s3"
  FIRMUPS_STORAGE_S3_ENDPOINT: {{ .Values.storage.s3Endpoint | quote }}
  FIRMUPS_STORAGE_S3_REGION: {{ .Values.storage.region | quote }}
  FIRMUPS_STORAGE_S3_BUCKET: {{ .Values.storage.bucket | quote }}
  FIRMUPS_LOG_PATH: {{ .Values.app.logPath | quote }}
  FIRMUPS_LOG_MAX_DAYS: {{ .Values.app.logMaxDays | quote }}
